### ISSUE TITLE
Create an errors schema

### ISSUE THREAD

**Issue by kahowell** [RedHatInsights/event-schemas#3]
E.g. (with missing fields):

```json
{
  "type": "com.redhat.console.puptoo.payload-rejected",
  "subject": "urn:redhat:console:ingress_payload:d3ef449d-f799-4883-b36f-32011000d5b8",
  "dataschema": "https://console.redhat.com/api/schemas/core/v1/errors.json"
  "data": {
    "errors": [{
      "code": "PUPTOO1001",
      "message": "Unable to unpack the payload archive."
    }]
  }
}
```

**Comment by beav** [comment]
@kahowell randy had a good point which was that some issues are errors, and some are valid failure states. For example, if a system has an unparsable config file, the system is in a failure state and we should generate an event when we find out about it. Same for disk full, etc.

**Comment by kruai** [comment]
> @kahowell randy had a good point which was that some issues are errors, and some are valid failure states. For example, if a system has an unparsable config file, the system is in a failure state and we should generate an event when we find out about it. Other stuff in this category might be full partition, etc.

Yeah - so these kinds of events would be produced when the data can be parsed but has invalid fields or values, right?

**Comment by beav** [comment]
> > @kahowell randy had a good point which was that some issues are errors, and some are valid failure states. For example, if a system has an unparsable config file, the system is in a failure state and we should generate an event when we find out about it. Other stuff in this category might be full partition, etc.
> 
> Yeah - so these kinds of events would be produced when the data can be parsed but has invalid fields or values, right?

ya, like especially if we can say "parser X failed when parsing file Y" or similar.
